project_description: Proof of concept for graphql in cashback microservice
project_name: graphql-spike-jennifer-black
python_version: '3.8'
sentry_dsn_integration: null
sentry_dsn_integration_au: null
sentry_dsn_live: null
sentry_dsn_singletenant_test: null
sentry_dsn_tdbank: null
sentry_dsn_test: null
sentry_dsn_test_au: null
